#!/usr/bin/env node

var chalk = require('chalk')
var args = require('yargs').argv
var Copper = require('./lib/copper')
var copper = new Copper()

var walletFile = args.wallet || process.env.HOME+"/.bitcoin/wallet.dat"
var keys = copper.loadBitcoinWallet(walletFile)

console.log('wallet:', walletFile)
console.log('', chalk.green(keys.length), 'keys read.')
